import { api } from "./api";

/** Mirrors the backend `ReportType` enum (`report.entity.ts`) — same values,
 * same order. The "Outro" option requires `reportTypeOther`. */
export const REPORT_TYPES = [
  { value: "laudo_medico", label: "Laudo médico" },
  { value: "laudo_exame", label: "Laudo de exame" },
  { value: "relatorio_medico", label: "Relatório médico" },
  { value: "relatorio_acompanhamento", label: "Relatório de acompanhamento" },
  { value: "laudo_administrativo", label: "Laudo para fins administrativos" },
  { value: "laudo_trabalhista", label: "Laudo para fins trabalhistas" },
  { value: "laudo_previdenciario", label: "Laudo para fins previdenciários" },
  { value: "outro", label: "Outro" },
] as const;

export type ReportType = (typeof REPORT_TYPES)[number]["value"];

export function reportTypeLabel(
  type: ReportType | string,
  other?: string | null,
): string {
  if (type === "outro") return other?.trim() || "Outro";
  return REPORT_TYPES.find((t) => t.value === type)?.label || type;
}

/** Document lifecycle, mirroring the backend `DocumentStatus`. `signed` is
 * only ever set by a real signature provider — none exists yet, so nothing
 * in the UI should present a document as digitally signed on its own. */
export type DocumentStatus =
  | "draft"
  | "generated"
  | "sent"
  | "signed"
  | "canceled";

export type SignatureStatus =
  | "none"
  | "pending"
  | "signed"
  | "failed"
  | "rejected";

export const REPORT_STATUS_LABELS: Record<DocumentStatus, string> = {
  draft: "Rascunho",
  generated: "Gerado",
  sent: "Enviado",
  signed: "Assinado",
  canceled: "Cancelado",
};

/** Tiptap/ProseMirror JSON. Opaque here — the editor produces it and the
 * backend's `prosemirror-to-pdfkit` renderer consumes it. */
export type RichTextDoc = {
  type: string;
  content?: unknown[];
  [key: string]: unknown;
};

/** The nine clinical fields are rich text; everything else is plain. */
export const REPORT_CLINICAL_FIELDS = [
  { key: "chiefComplaint", label: "Queixa / Motivo" },
  { key: "clinicalHistory", label: "História clínica" },
  { key: "physicalExam", label: "Exame físico" },
  { key: "complementaryExams", label: "Exames complementares" },
  { key: "results", label: "Resultados" },
  { key: "diagnosis", label: "Diagnóstico" },
  { key: "conclusion", label: "Conclusão" },
  { key: "recommendations", label: "Conduta / Recomendações" },
  { key: "observations", label: "Observações" },
] as const;

export type ReportClinicalField =
  (typeof REPORT_CLINICAL_FIELDS)[number]["key"];

export interface Report {
  id: string;
  doctorId: string;
  patientId: string | null;
  dependentId: string | null;
  appointmentId: string | null;
  reportType: ReportType;
  reportTypeOther: string | null;
  issueDate: string;
  relatedServiceDate: string | null;
  purpose: string | null;
  title: string;
  doctorNameSnapshot: string;
  doctorCrmSnapshot: string;
  doctorSpecialtySnapshot: string | null;
  patientNameSnapshot: string;
  patientCpfSnapshot: string | null;
  patientBirthDateSnapshot: string | null;
  patientGenderSnapshot: string | null;
  chiefComplaint: RichTextDoc | null;
  clinicalHistory: RichTextDoc | null;
  physicalExam: RichTextDoc | null;
  complementaryExams: RichTextDoc | null;
  results: RichTextDoc | null;
  diagnosis: RichTextDoc | null;
  conclusion: RichTextDoc | null;
  recommendations: RichTextDoc | null;
  observations: RichTextDoc | null;
  status: DocumentStatus;
  /** PDF generated by Hispora from this laudo's structured content. */
  documentUrl: string | null;
  /** A pre-existing document uploaded by the doctor (issued outside
   * Hispora). Kept separate from `documentUrl` so the UI never presents an
   * upload as something the platform generated. */
  fileUrl: string | null;
  documentHash: string | null;
  signatureStatus: SignatureStatus;
  signatureProvider: string | null;
  signedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ReportPayload {
  patientId?: string;
  dependentId?: string;
  appointmentId?: string;
  reportType: ReportType;
  reportTypeOther?: string;
  issueDate?: string;
  relatedServiceDate?: string;
  purpose?: string;
  title: string;
  chiefComplaint?: RichTextDoc;
  clinicalHistory?: RichTextDoc;
  physicalExam?: RichTextDoc;
  complementaryExams?: RichTextDoc;
  results?: RichTextDoc;
  diagnosis?: RichTextDoc;
  conclusion?: RichTextDoc;
  recommendations?: RichTextDoc;
  observations?: RichTextDoc;
}

/** The document structure the backend renders the PDF from — returned by
 * `GET /reports/:id/preview` so the on-screen preview matches the PDF
 * instead of being rebuilt (and drifting) on the frontend. */
export interface DocumentSpec {
  documentType: "prescription" | "report" | "exam";
  title: string;
  doctor: { name: string; crm: string; specialty?: string | null };
  patient: {
    name: string;
    cpf?: string | null;
    birthDate?: string | null;
    gender?: string | null;
  };
  issueDate: string;
  sections: Array<
    | {
        kind: "key-values";
        heading?: string;
        items: Array<{ label: string; value: string }>;
      }
    | { kind: "rich-text"; heading: string; content: RichTextDoc | null }
    | { kind: "plain-text"; heading?: string; text: string }
  >;
  signatureStatus: SignatureStatus;
}

export interface ReportFilters {
  patientId?: string;
  status?: DocumentStatus;
  startDate?: string;
  endDate?: string;
  search?: string;
}

export const reportsApi = {
  list: (filters: ReportFilters = {}): Promise<Report[]> => {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(filters)) {
      if (value) params.set(key, value);
    }
    const qs = params.toString();
    return api(`/reports${qs ? `?${qs}` : ""}`);
  },

  getById: (id: string): Promise<Report> => api(`/reports/${id}`),

  create: (data: ReportPayload): Promise<Report> =>
    api("/reports", { method: "POST", body: data }),

  update: (id: string, data: Partial<ReportPayload>): Promise<Report> =>
    api(`/reports/${id}`, { method: "PATCH", body: data }),

  remove: (id: string): Promise<{ message: string }> =>
    api(`/reports/${id}`, { method: "DELETE" }),

  cancel: (id: string): Promise<Report> =>
    api(`/reports/${id}/cancel`, { method: "POST" }),

  /** Uploads a pre-existing laudo document. Separate from `create`/`update`
   * because the clinical fields are rich-text objects that wouldn't survive
   * a multipart round-trip. */
  attachFile: (id: string, file: File): Promise<Report> => {
    const formData = new FormData();
    formData.append("file", file);
    return api(`/reports/${id}/file`, {
      method: "POST",
      body: formData,
      isFormData: true,
    });
  },

  removeFile: (id: string): Promise<Report> =>
    api(`/reports/${id}/file`, { method: "DELETE" }),

  /** Laudos filed under a patient's medical record — mirrors how the other
   * record tabs (atestados, exames) load their data. */
  listForPatient: (patientId: string): Promise<Report[]> =>
    api(`/patients/${patientId}/reports`),

  preview: (id: string): Promise<DocumentSpec> => api(`/reports/${id}/preview`),

  generatePdf: (id: string): Promise<Report> =>
    api(`/reports/${id}/generate-pdf`, { method: "POST" }),

  /** "Enviar sem assinatura digital" — delivers the already-generated PDF
   * to the patient as-is. */
  send: (id: string): Promise<Report> =>
    api(`/reports/${id}/send`, { method: "POST" }),

  /** "Assinar digitalmente e enviar", step 1 — starts the (simulated)
   * signature request and returns the URL to open in a new tab. */
  requestSignature: (
    id: string,
  ): Promise<{ report: Report; signingUrl: string }> =>
    api(`/reports/${id}/request-signature`, { method: "POST" }),

  /** Step 2, called from the signature-simulator page once "signed". */
  confirmSignature: (id: string, externalSignatureId: string): Promise<Report> =>
    api(`/reports/${id}/confirm-signature`, {
      method: "POST",
      body: { externalSignatureId },
    }),
};
